export {
  createAdminResource,
  createResourceDownloadLink,
  deleteAdminResource,
  deleteResourceFile,
  deleteResourceImage,
  deleteResourceVideo,
  fetchAdminResourceDetail,
  fetchAdminResources,
  fetchResourceAccessList,
  fetchResourceDetail,
  fetchResourceMeta,
  fetchResourcePedagogy,
  fetchResourcesSummary,
  grantResourceAccess,
  reorderResourceImages,
  revokeResourceAccess,
  toggleResourceFavorite,
  updateAdminResource,
  updateResourceImage,
  updateResourcePedagogy,
  updateResourceVideo,
  uploadResourceFileWithProgress,
  uploadResourceImage,
  uploadResourceVideo,
} from './resources-client'
