### Testar matriculando em um produto
POST http://localhost:3000/api/v1/enroll
x-api-key: 37007c82ba6a16asd343304dd6454996712577acc99b141a44cdb3b5b454ccb432b
Content-Type: application/json

{
  "store": "prof-didatica",
  "name": "Individual",
  "email": "individual@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482100",
  "product_ids": [30200956]
}

### Testar matriculando em dois produtos
POST http://localhost:3000/api/v1/enroll
x-api-key: 37007c82ba6a16asd343304dd6454996712577acc99b141a44cdb3b5b454ccb432b
Content-Type: application/json

{
  "store": "prof-didatica",
  "name": "Multi Produtos",
  "email": "multi@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482101",
  "product_ids": [37235525,30200121]
}

### Testar com Plano Semestral
POST http://localhost:3000/api/v1/enroll
x-api-key: 37007c82ba6a16asd343304dd6454996712577acc99b141a44cdb3b5b454ccb432b
Content-Type: application/json

{
  "store": "prof-didatica",
  "name": "Plano Semestral",
  "email": "semestral@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482102",
  "product_ids": [42643883]
}


### Testar com Plano Anual
POST http://localhost:3000/api/v1/enroll
x-api-key: 37007c82ba6a16asd343304dd649f54996712577acc99b141a44cdb3b5b454ccb432b
Content-Type: application/json

{
  "store": "prof-didatica",
  "name": "Plano Anual",
  "email": "anual@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482103",
  "product_ids": [42643885]
}
