@host = {{$dotenv NEXT_PUBLIC_APP_URL}}
@apiKey = {{$dotenv WEBHOOK_API_KEY}}
@contentType = application/json

### Testar matriculando em um produto
POST {{host}}/api/v1/enroll HTTP/1.1
x-api-key: {{apiKey}}
Content-Type: {{contentType}}

{
  "store": "prof-didatica",
  "name": "Individual",
  "email": "individual@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482100",
  "product_ids": [30200956]
}

### Testar matriculando em dois produtos
POST {{host}}/api/v1/enroll HTTP/1.1
x-api-key: {{apiKey}}
Content-Type: {{contentType}}

{
  "store": "prof-didatica",
  "name": "Multi Produtos",
  "email": "multi@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482112",
  "product_ids": [37235525,30200121]
}

### Testar com Plano Semestral
POST {{host}}/api/v1/enroll HTTP/1.1
x-api-key: {$apiKey}
Content-Type: {{contentType}}

{
  "store": "prof-didatica",
  "name": "Plano Semestral",
  "email": "semestral@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482113",
  "product_ids": [42643883]
}

### Testar com Plano Anual
POST {{host}}/api/v1/enroll HTTP/1.1
x-api-key: {$apiKey}}
Content-Type: {{contentType}}

{
  "store": "prof-didatica",
  "name": "Plano Anual",
  "email": "anual@mail.com",
  "cpf": "12345678900",
  "whatsapp": "61982482114",
  "product_ids": [42643885]
}

### Testar saúde
GET {{host}}/api/health




