export * from './bulk-service'

export * from './create-service'
export * from './delete-service'
export * from './detail-service'
export * from './file-service'
export * from './image-service'
export * from './list-service'
export * from './update-service'
export * from './video-service'
export * from './pedagogy-service'
